%%
bits=zeros(864,Lmax_*2);
% payload generation
for issb=0:(Lmax_*2-1)
    issb_bin=int2bit(mod(issb,Lmax_),6,true);
    bits(:,issb+1)=PbchGenerator.generatePbch(...
        MIB,...
        SFN,...
        issb>=Lmax_,...
        [k_SSB>=16 0 0],...
        NCellId, ...
        Lmax_...
        );
end
%% frame generation
rg=ResourceTransmitter.GenerateFrame(bits,NCellId,caseL,pointA,tran_bandwidth,toff,foff,[1,1,0.85,0.9]);
% samples per symbol (~sample rate)
SPS=size(rg,1);
%% generating time-domain complex signal and cropping it
samples=OfdmTransceiver.ResourceGrid2ComlexTime(rg);
samples=samples(samples_offset:samples_offset+symbs_received*SPS-1);